# -*- coding: utf-8 -*-
"""language tran.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XTchdKgUWrrzzFnhsz9UdJwwHl6WzsZ
"""

# Install required libraries
!pip install googletrans==4.0.0-rc1
!pip install gtts

# Import required libraries
from googletrans import Translator
from gtts import gTTS
from IPython.display import Audio, display

# Function to translate text and convert to speech
def translate_and_play():
    # Input text for translation
    text = input_text.value

    # Get selected languages
    src_lang = language_codes[input_language_dropdown.value]
    dest_lang = language_codes[translate_language_dropdown.value]

    # Translate the text
    translator = Translator()
    translation = translator.translate(text, src=src_lang, dest=dest_lang)

    # Output translated text
    output_text.value = translation.text

    # Convert translated text to speech
    tts = gTTS(text=translation.text, lang=dest_lang)
    tts.save("translation.mp3")

    # Play the audio of the translated text
    display(Audio("translation.mp3", autoplay=True))

# Language codes for the dropdown options
language_codes = {
    'English': 'en',
    'Hindi': 'hi',
    'French': 'fr',
    'German': 'de',
    'Spanish': 'es',
    'Telugu': 'te',
    'Korean': 'ko',
    'Kannada': 'kn',
    'Tamil': 'ta',
    'Bengali': 'bn'
}

# Create widgets for user interaction
import ipywidgets as widgets

input_text = widgets.Textarea(
    value='',
    placeholder='Enter text to translate...',
    description='Input:',
    layout=widgets.Layout(width='600px', height='100px')
)

output_text = widgets.Textarea(
    value='',
    placeholder='Translation will appear here...',
    description='Output:',
    layout=widgets.Layout(width='600px', height='100px'),
    disabled=True
)

input_language_dropdown = widgets.Dropdown(
    options=list(language_codes.keys()),
    value='English',
    description='From:'
)

translate_language_dropdown = widgets.Dropdown(
    options=list(language_codes.keys()),
    value='Hindi',
    description='To:'
)

translate_button = widgets.Button(
    description="Translate and Play",
    button_style='success'
)

# Link the button to the function
translate_button.on_click(lambda x: translate_and_play())

# Display the widgets
display(widgets.VBox([
    widgets.HBox([input_language_dropdown, translate_language_dropdown]),
    input_text,
    translate_button,
    output_text
]))